name: icloud-for-linux
version: '0.14'
summary: iCloud for Linux
description: iCloud for Linux

grade: stable
confinement: strict
base: core20

parts:
  icloud-for-linux:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr

apps:
  mail:
    command: usr/bin/icloud-for-linux mail
    extensions: &extensions
      - gnome-3-38
    plugs: &plugs
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - screen-inhibit-control
      - x11
    environment: &environment
      TMPDIR: $XDG_RUNTIME_DIR
  contacts:
    command: usr/bin/icloud-for-linux contacts
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  calendar:
    command: usr/bin/icloud-for-linux calendar
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  photos:
    command: usr/bin/icloud-for-linux photos
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  drive:
    command: usr/bin/icloud-for-linux iclouddrive
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  notes:
    command: usr/bin/icloud-for-linux notes
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  reminders:
    command: usr/bin/icloud-for-linux reminders
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  pages:
    command: usr/bin/icloud-for-linux pages
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  numbers:
    command: usr/bin/icloud-for-linux numbers
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  keynote:
    command: usr/bin/icloud-for-linux keynote
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  find-devices:
    command: usr/bin/icloud-for-linux find
    extensions: *extensions
    plugs: *plugs
    environment: *environment
