name: icloud-for-linux
version: '0.7'
summary: iCloud for Linux
description: iCloud for Linux

grade: stable
confinement: strict
base: core18

layout:
  /usr/share/qt5:
    bind: $SNAP/usr/share/qt5

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]

  icloud-for-linux:
    after: [desktop-qt5]
    source: .
    plugin: qmake
    build-packages:
      - qtdeclarative5-dev
    stage-packages:
      - qml-module-qtquick2
      - qml-module-qtquick-controls
      - qml-module-qtquick-window2
      - qml-module-qtwebengine
      - qml-module-qtquick-dialogs

  dump:
    source: dump
    plugin: dump

apps:
  mail:
    command: icloud-for-linux.launcher mail "iCloud Mail"
    plugs: &plugs
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - screen-inhibit-control
      - x11
    environment: &environment
      DISABLE_WAYLAND: 1
  contacts:
    command: icloud-for-linux.launcher contacts "iCloud Contacts"
    plugs: *plugs
    environment: *environment
  calendar:
    command: icloud-for-linux.launcher calendar "iCloud Calendar"
    plugs: *plugs
    environment: *environment
  photos:
    command: icloud-for-linux.launcher photos "iCloud Photos"
    plugs: *plugs
    environment: *environment
  drive:
    command: icloud-for-linux.launcher iclouddrive "iCloud Drive"
    plugs: *plugs
    environment: *environment
  notes:
    command: icloud-for-linux.launcher notes "iCloud Notes"
    plugs: *plugs
    environment: *environment
  reminders:
    command: icloud-for-linux.launcher reminders "iCloud Reminders"
    plugs: *plugs
    environment: *environment
  pages:
    command: icloud-for-linux.launcher pages "iCloud Pages"
    plugs: *plugs
    environment: *environment
  numbers:
    command: icloud-for-linux.launcher numbers "iCloud Numbers"
    plugs: *plugs
    environment: *environment
  keynote:
    command: icloud-for-linux.launcher keynote "iCloud Keynote"
    plugs: *plugs
    environment: *environment
  find-my-friends:
    command: icloud-for-linux.launcher fmf "iCloud Find My Friends"
    plugs: *plugs
    environment: *environment
  find-my-iphone:
    command: icloud-for-linux.launcher find "iCloud Find My iPhone"
    plugs: *plugs
    environment: *environment
