name: icloud-for-linux
version: '0.12'
summary: iCloud for Linux
description: iCloud for Linux

grade: stable
confinement: strict
base: core20

parts:
  icloud-for-linux:
    plugin: nil
    source: .
    override-build: |
        npm install electron electron-packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./icloud-for-linux-linux-* $SNAPCRAFT_PART_INSTALL/icloud-for-linux
    build-snaps:
    - node/16/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4

apps:
  mail:
    command: icloud-for-linux/icloud-for-linux --no-sandbox mail
    extensions: &extensions
      - gnome-3-38
    plugs: &plugs
      - browser-support
      - desktop
      - desktop-legacy
      - home
      - network
      - opengl
      - screen-inhibit-control
      - x11
    environment: &environment
      TMPDIR: $XDG_RUNTIME_DIR
  contacts:
    command: icloud-for-linux/icloud-for-linux --no-sandbox contacts
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  calendar:
    command: icloud-for-linux/icloud-for-linux --no-sandbox calendar
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  photos:
    command: icloud-for-linux/icloud-for-linux --no-sandbox photos
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  drive:
    command: icloud-for-linux/icloud-for-linux --no-sandbox iclouddrive
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  notes:
    command: icloud-for-linux/icloud-for-linux --no-sandbox notes
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  reminders:
    command: icloud-for-linux/icloud-for-linux --no-sandbox reminders
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  pages:
    command: icloud-for-linux/icloud-for-linux --no-sandbox pages
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  numbers:
    command: icloud-for-linux/icloud-for-linux --no-sandbox numbers
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  keynote:
    command: icloud-for-linux/icloud-for-linux --no-sandbox keynote
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  find-my-friends:
    command: icloud-for-linux/icloud-for-linux --no-sandbox fmf
    extensions: *extensions
    plugs: *plugs
    environment: *environment
  find-my-iphone:
    command: icloud-for-linux/icloud-for-linux --no-sandbox find
    extensions: *extensions
    plugs: *plugs
    environment: *environment
